<template lang="pug">
el-container
  el-main
    el-row
      el-col(:span="6")
        el-form-item(label="树的类型:" size="large")
          el-select(v-model="appStore.states.graphModeSelect",placeholder="树的类型",style="width: 100%",size='large',@change='updateChart')
            el-option(v-for="item in graphMode",:key="item.text",:label="item.text",:value="item.value")    
      el-col(:span="6")
        el-form-item(label="是否展示标签:" size="large")
          el-switch(v-model="labelShow"  size="large"  active-text="Open" inactive-text="Close" @change='updateChart')

    el-row
      el-col(:span="24")
        #echart1.echartForce
    el-row 
      NoteBook(storagekey="subject-algorithm-tree",:editMode="true")
</template>

<script lang="ts">
export default {
  name: "subject-algorithm-tree",
  autoIndex: true,
  text: "MAG 学科树",
  update: "2023-01-09T01:01:01.429Z",
};
</script>

<script setup lang="ts">
import { homeStore, dynamicStore } from "@/pinia/modules/pageStore";
import NoteBook from "@/components/NoteBook.vue";
import { localService } from "@/utils/requests";
import { reactive, ref, onMounted } from "vue";
import colormap from "colormap";
import _ from "lodash";
import * as echarts from "echarts";
import { extendEchartsOpts } from "@/utils/model";
import { ElMessage } from "element-plus";

const appHomeStore = homeStore();
appHomeStore.title = "subject algorithm tree";
let dataset: any;
const paperLoading = ref(false);
const labelShow = ref(false);

const appStore = dynamicStore("subject-algorithm-tree-2022", {
  graphModeSelect: 0,
});

const graphMode = [
  {
    text: "一级学科的最小生成树",
    value: 0,
  },
  {
    text: "一级学科的最小生成树+距离最近的18条边连接",
    value: 1,
  },
  {
    text: "二级293学科的最小生成树",
    value: 2,
  },
  // {
  //   text: "二级学科的最小生成树+top连接",
  //   value: 3,
  // },
];

let myChartObjs: echarts.ECharts[] = [];

const updateChart = _.debounce(async () => {
  let graphTitle = "";
  let graph: any;
  if (appStore.states.graphModeSelect === 0) {
    graph = {
      nodes: [
        { id: 0, name: "Business" },
        { id: 1, name: "Economics" },
        { id: 2, name: "Sociology" },
        { id: 3, name: "Political science" },
        { id: 4, name: "Geology" },
        { id: 5, name: "Environmental science" },
        { id: 6, name: "Medicine" },
        { id: 7, name: "Biology" },
        { id: 8, name: "Geography" },
        { id: 9, name: "Chemistry" },
        { id: 10, name: "Art" },
        { id: 11, name: "History" },
        { id: 12, name: "Mathematics" },
        { id: 13, name: "Computer science" },
        { id: 14, name: "Philosophy" },
        { id: 15, name: "Psychology" },
        { id: 16, name: "Materials science" },
        { id: 17, name: "Physics" },
        { id: 18, name: "Engineering disciplines" },
      ],
      links: [
        { source: 0, target: 1 },
        { source: 2, target: 3 },
        { source: 2, target: 1 },
        { source: 2, target: 11 },
        { source: 4, target: 5 },
        { source: 4, target: 8 },
        { source: 6, target: 7 },
        { source: 6, target: 15 },
        { source: 8, target: 11 },
        { source: 9, target: 7 },
        { source: 10, target: 11 },
        { source: 10, target: 14 },
        { source: 12, target: 13 },
        { source: 13, target: 18 },
        { source: 15, target: 2 },
        { source: 16, target: 17 },
        { source: 16, target: 9 },
        { source: 17, target: 18 },
      ],
    };
    graphTitle = "一级学科的最小生成树";
  } else if (appStore.states.graphModeSelect === 1) {
    graphTitle = "一级学科的最小生成树";
    graph = {
      nodes: [
        { id: 0, name: "Business" },
        { id: 1, name: "Economics" },
        { id: 2, name: "Sociology" },
        { id: 3, name: "Political science" },
        { id: 4, name: "Geology" },
        { id: 5, name: "Environmental science" },
        { id: 6, name: "Medicine" },
        { id: 7, name: "Biology" },
        { id: 8, name: "Geography" },
        { id: 9, name: "Chemistry" },
        { id: 10, name: "Art" },
        { id: 11, name: "History" },
        { id: 12, name: "Mathematics" },
        { id: 13, name: "Computer science" },
        { id: 14, name: "Philosophy" },
        { id: 15, name: "Psychology" },
        { id: 16, name: "Materials science" },
        { id: 17, name: "Physics" },
        { id: 18, name: "Engineering disciplines" },
      ],
      links: [
        { source: 0, target: 1, lineStyle: { width: 3 } },
        { source: 2, target: 3, lineStyle: { width: 3 } },
        { source: 2, target: 1, lineStyle: { width: 3 } },
        { source: 2, target: 11, lineStyle: { width: 3 } },
        { source: 4, target: 5, lineStyle: { width: 3 } },
        { source: 4, target: 8, lineStyle: { width: 3 } },
        { source: 6, target: 7, lineStyle: { width: 3 } },
        { source: 6, target: 15, lineStyle: { width: 3 } },
        { source: 8, target: 11, lineStyle: { width: 3 } },
        { source: 9, target: 7, lineStyle: { width: 3 } },
        { source: 10, target: 11, lineStyle: { width: 3 } },
        { source: 10, target: 14, lineStyle: { width: 3 } },
        { source: 12, target: 13, lineStyle: { width: 3 } },
        { source: 13, target: 18, lineStyle: { width: 3 } },
        { source: 15, target: 2, lineStyle: { width: 3 } },
        { source: 16, target: 17, lineStyle: { width: 3 } },
        { source: 16, target: 9, lineStyle: { width: 3 } },
        { source: 17, target: 18, lineStyle: { width: 3 } },
        { source: 1, target: 3, lineStyle: { width: 1 } },
        { source: 5, target: 8, lineStyle: { width: 1 } },
        { source: 0, target: 3, lineStyle: { width: 1 } },
        { source: 0, target: 2, lineStyle: { width: 1 } },
        { source: 11, target: 14, lineStyle: { width: 1 } },
        { source: 3, target: 11, lineStyle: { width: 1 } },
        { source: 16, target: 18, lineStyle: { width: 1 } },
        { source: 2, target: 14, lineStyle: { width: 1 } },
        { source: 3, target: 14, lineStyle: { width: 1 } },
        { source: 12, target: 18, lineStyle: { width: 1 } },
        { source: 1, target: 8, lineStyle: { width: 1 } },
        { source: 12, target: 17, lineStyle: { width: 1 } },
        { source: 6, target: 9, lineStyle: { width: 1 } },
        { source: 2, target: 10, lineStyle: { width: 1 } },
        { source: 3, target: 8, lineStyle: { width: 1 } },
        { source: 2, target: 8, lineStyle: { width: 1 } },
        { source: 3, target: 10, lineStyle: { width: 1 } },
        { source: 4, target: 11, lineStyle: { width: 1 } },
      ],
    };
  } else if (appStore.states.graphModeSelect === 2) {
    graph = {
      nodes: [
        { id: 0, name: "Inorganic chemistry", category: 3 },
        { id: 1, name: "Organic chemistry", category: 3 },
        { id: 2, name: "Analytical chemistry", category: 3 },
        { id: 3, name: "Anatomy", category: 13 },
        { id: 4, name: "Veterinary medicine", category: 13 },
        { id: 5, name: "Macroeconomics", category: 5 },
        { id: 6, name: "Monetary economics", category: 5 },
        { id: 7, name: "Endocrinology", category: 13 },
        { id: 8, name: "Internal medicine", category: 13 },
        { id: 9, name: "Atmospheric sciences", category: 15 },
        { id: 10, name: "Meteorology", category: 15 },
        { id: 11, name: "Geochemistry", category: 9 },
        { id: 12, name: "Geomorphology", category: 9 },
        { id: 13, name: "International trade", category: 5 },
        { id: 14, name: "International economics", category: 5 },
        { id: 15, name: "Economic policy", category: 5 },
        { id: 16, name: "Discrete mathematics", category: 12 },
        { id: 17, name: "Combinatorics", category: 12 },
        { id: 18, name: "Gynecology", category: 13 },
        { id: 19, name: "Obstetrics", category: 13 },
        { id: 20, name: "Paleontology", category: 9 },
        { id: 21, name: "Computer network", category: 4 },
        { id: 22, name: "Distributed computing", category: 4 },
        { id: 23, name: "Real-time computing", category: 4 },
        { id: 24, name: "Financial economics", category: 5 },
        { id: 25, name: "Economy", category: 5 },
        { id: 26, name: "Microeconomics", category: 5 },
        { id: 27, name: "Developmental psychology", category: 17 },
        { id: 28, name: "Social psychology", category: 17 },
        { id: 29, name: "Climatology", category: 9 },
        { id: 30, name: "Development economics", category: 5 },
        { id: 31, name: "Political economy", category: 18 },
        { id: 32, name: "Algebra", category: 12 },
        { id: 33, name: "Pure mathematics", category: 12 },
        { id: 34, name: "Earth science", category: 9 },
        { id: 35, name: "Geophysics", category: 15 },
        { id: 36, name: "Geodesy", category: 9 },
        { id: 37, name: "Seismology", category: 9 },
        { id: 38, name: "Finance", category: 5 },
        { id: 39, name: "Mathematics education", category: 17 },
        { id: 40, name: "Pedagogy", category: 18 },
        { id: 41, name: "Economic system", category: 5 },
        { id: 42, name: "Market economy", category: 5 },
        { id: 43, name: "Petrology", category: 9 },
        { id: 44, name: "Financial system", category: 5 },
        { id: 45, name: "Control engineering", category: 6 },
        { id: 46, name: "Control theory", category: 12 },
        { id: 47, name: "Economic growth", category: 5 },
        { id: 48, name: "Particle physics", category: 15 },
        { id: 49, name: "Quantum electrodynamics", category: 15 },
        { id: 50, name: "Cancer research", category: 13 },
        { id: 51, name: "Oncology", category: 13 },
        { id: 52, name: "Clinical psychology", category: 17 },
        { id: 53, name: "Genetics", category: 1 },
        { id: 54, name: "Molecular biology", category: 1 },
        { id: 55, name: "Human\\u2013computer interaction", category: 4 },
        { id: 56, name: "Multimedia", category: 4 },
        { id: 57, name: "Topology", category: 12 },
        { id: 58, name: "Labour economics", category: 5 },
        { id: 59, name: "Computer vision", category: 4 },
        { id: 60, name: "Pattern recognition", category: 4 },
        { id: 61, name: "Agroforestry", category: 7 },
        { id: 62, name: "Forestry", category: 8 },
        { id: 63, name: "Emergency medicine", category: 13 },
        { id: 64, name: "Medical emergency", category: 13 },
        { id: 65, name: "Religious studies", category: 14 },
        { id: 66, name: "Theology", category: 14 },
        { id: 67, name: "Public administration", category: 16 },
        { id: 68, name: "Cell biology", category: 1 },
        { id: 69, name: "Mathematical physics", category: 15 },
        { id: 70, name: "Atomic physics", category: 15 },
        { id: 71, name: "Condensed matter physics", category: 15 },
        { id: 72, name: "Agricultural economics", category: 5 },
        { id: 73, name: "Natural resource economics", category: 5 },
        { id: 74, name: "Pathology", category: 13 },
        { id: 75, name: "Surgery", category: 13 },
        { id: 76, name: "Electrical engineering", category: 6 },
        { id: 77, name: "Electronic engineering", category: 6 },
        { id: 78, name: "Biochemistry", category: 3 },
        { id: 79, name: "Public economics", category: 5 },
        { id: 80, name: "Linguistics", category: 14 },
        { id: 81, name: "Natural language processing", category: 4 },
        { id: 82, name: "Business administration", category: 2 },
        { id: 83, name: "Marketing", category: 2 },
        { id: 84, name: "Programming language", category: 4 },
        { id: 85, name: "Software engineering", category: 6 },
        { id: 86, name: "Family medicine", category: 13 },
        { id: 87, name: "Nursing", category: 13 },
        { id: 88, name: "Keynesian economics", category: 5 },
        { id: 89, name: "Theoretical physics", category: 15 },
        { id: 90, name: "Commerce", category: 5 },
        { id: 91, name: "Industrial organization", category: 5 },
        { id: 92, name: "Classical mechanics", category: 15 },
        { id: 93, name: "Mechanics", category: 15 },
        { id: 94, name: "Cognitive psychology", category: 17 },
        { id: 95, name: "Gerontology", category: 13 },
        { id: 96, name: "Demography", category: 18 },
        { id: 97, name: "Psychiatry", category: 17 },
        { id: 98, name: "Psychotherapist", category: 17 },
        { id: 99, name: "Civil engineering", category: 6 },
        { id: 100, name: "Environmental engineering", category: 7 },
        { id: 101, name: "Astrophysics", category: 15 },
        { id: 102, name: "Astronomy", category: 15 },
        { id: 103, name: "Botany", category: 1 },
        { id: 104, name: "Ecology", category: 1 },
        { id: 105, name: "Quantum mechanics", category: 15 },
        { id: 106, name: "Public relations", category: 16 },
        { id: 107, name: "Agronomy", category: 1 },
        { id: 108, name: "Horticulture", category: 1 },
        { id: 109, name: "Actuarial science", category: 5 },
        { id: 110, name: "Machine learning", category: 4 },
        { id: 111, name: "Data mining", category: 4 },
        { id: 112, name: "Agricultural science", category: 7 },
        { id: 113, name: "Cognitive science", category: 17 },
        { id: 114, name: "Fishery", category: 1 },
        { id: 115, name: "Oceanography", category: 9 },
        { id: 116, name: "Telecommunications", category: 6 },
        { id: 117, name: "Environmental chemistry", category: 3 },
        { id: 118, name: "Socioeconomics", category: 18 },
        { id: 119, name: "Computer hardware", category: 4 },
        { id: 120, name: "Embedded system", category: 6 },
        { id: 121, name: "Computational chemistry", category: 3 },
        { id: 122, name: "Physical chemistry", category: 3 },
        { id: 123, name: "Immunology", category: 13 },
        { id: 124, name: "Computer architecture", category: 4 },
        { id: 125, name: "Accounting", category: 5 },
        { id: 126, name: "Parallel computing", category: 4 },
        { id: 127, name: "Composite material", category: 11 },
        { id: 128, name: "Metallurgy", category: 11 },
        { id: 129, name: "Knowledge management", category: 4 },
        { id: 130, name: "Economic geography", category: 8 },
        { id: 131, name: "Regional science", category: 18 },
        { id: 132, name: "Artificial intelligence", category: 4 },
        { id: 133, name: "Positive economics", category: 5 },
        { id: 134, name: "Waste management", category: 6 },
        { id: 135, name: "Aeronautics", category: 6 },
        { id: 136, name: "Aerospace engineering", category: 6 },
        { id: 137, name: "Performance art", category: 0 },
        { id: 138, name: "Visual arts", category: 0 },
        { id: 139, name: "Operating system", category: 4 },
        { id: 140, name: "Environmental economics", category: 5 },
        { id: 141, name: "Archaeology", category: 10 },
        { id: 142, name: "Literature", category: 0 },
        { id: 143, name: "Art history", category: 10 },
        { id: 144, name: "Zoology", category: 1 },
        { id: 145, name: "Law and economics", category: 18 },
        { id: 146, name: "Speech recognition", category: 4 },
        { id: 147, name: "Management science", category: 6 },
        { id: 148, name: "Nuclear physics", category: 15 },
        { id: 149, name: "Chemical physics", category: 15 },
        { id: 150, name: "World Wide Web", category: 4 },
        { id: 151, name: "Demographic economics", category: 5 },
        { id: 152, name: "Hydrology", category: 9 },
        { id: 153, name: "Soil science", category: 9 },
        { id: 154, name: "Information retrieval", category: 4 },
        { id: 155, name: "Environmental planning", category: 8 },
        { id: 156, name: "Environmental resource management", category: 7 },
        { id: 157, name: "Operations management", category: 6 },
        { id: 158, name: "Physical geography", category: 8 },
        { id: 159, name: "Neoclassical economics", category: 5 },
        { id: 160, name: "Computer security", category: 4 },
        { id: 161, name: "Ancient history", category: 10 },
        { id: 162, name: "Classics", category: 10 },
        { id: 163, name: "Microbiology", category: 1 },
        { id: 164, name: "Virology", category: 13 },
        { id: 165, name: "Mechanical engineering", category: 6 },
        { id: 166, name: "Internet privacy", category: 4 },
        { id: 167, name: "Operations research", category: 12 },
        { id: 168, name: "Algorithm", category: 12 },
        { id: 169, name: "Mathematical optimization", category: 12 },
        { id: 170, name: "Biophysics", category: 1 },
        { id: 171, name: "Pharmacology", category: 13 },
        { id: 172, name: "Physiology", category: 13 },
        { id: 173, name: "Theoretical computer science", category: 4 },
        { id: 174, name: "Nuclear magnetic resonance", category: 15 },
        { id: 175, name: "Traditional medicine", category: 13 },
        { id: 176, name: "Mathematical economics", category: 12 },
        { id: 177, name: "Welfare economics", category: 5 },
        { id: 178, name: "Molecular physics", category: 15 },
        { id: 179, name: "Database", category: 4 },
        { id: 180, name: "Gender studies", category: 18 },
        { id: 181, name: "Media studies", category: 18 },
        { id: 182, name: "Remote sensing", category: 9 },
        { id: 183, name: "Aesthetics", category: 14 },
        { id: 184, name: "Economic history", category: 10 },
        { id: 185, name: "Law", category: 16 },
        { id: 186, name: "Advertising", category: 2 },
        { id: 187, name: "Structural engineering", category: 6 },
        { id: 188, name: "Geotechnical engineering", category: 9 },
        { id: 189, name: "Anthropology", category: 18 },
        { id: 190, name: "Environmental protection", category: 8 },
        { id: 191, name: "Social science", category: 18 },
        { id: 192, name: "Neuroscience", category: 17 },
        { id: 193, name: "Psychoanalysis", category: 17 },
        { id: 194, name: "Gastroenterology", category: 13 },
        { id: 195, name: "General surgery", category: 13 },
        { id: 196, name: "Medical education", category: 13 },
        { id: 197, name: "Anesthesia", category: 13 },
        { id: 198, name: "Cardiology", category: 13 },
        { id: 199, name: "Systems engineering", category: 6 },
        { id: 200, name: "Engineering management", category: 6 },
        { id: 201, name: "Process management", category: 6 },
        { id: 202, name: "Photochemistry", category: 3 },
        { id: 203, name: "Nuclear medicine", category: 13 },
        { id: 204, name: "Radiology", category: 13 },
        { id: 205, name: "Environmental health", category: 13 },
        { id: 206, name: "Intensive care medicine", category: 13 },
        { id: 207, name: "Communication", category: 18 },
        { id: 208, name: "Industrial engineering", category: 6 },
        { id: 209, name: "Mathematical analysis", category: 12 },
        { id: 210, name: "Polymer chemistry", category: 11 },
        { id: 211, name: "Polymer science", category: 11 },
        { id: 212, name: "Ophthalmology", category: 13 },
        { id: 213, name: "Optometry", category: 13 },
        { id: 214, name: "Epistemology", category: 14 },
        { id: 215, name: "Computer engineering", category: 6 },
        { id: 216, name: "Ethnology", category: 18 },
        { id: 217, name: "Applied mathematics", category: 12 },
        { id: 218, name: "Mineralogy", category: 9 },
        { id: 219, name: "Physical therapy", category: 13 },
        { id: 220, name: "Optoelectronics", category: 15 },
        { id: 221, name: "Optics", category: 15 },
        { id: 222, name: "Computational biology", category: 1 },
        { id: 223, name: "Bioinformatics", category: 1 },
        { id: 224, name: "Evolutionary biology", category: 1 },
        { id: 225, name: "Econometrics", category: 12 },
        { id: 226, name: "Animal science", category: 1 },
        { id: 227, name: "Food science", category: 3 },
        { id: 228, name: "Medical physics", category: 15 },
        { id: 229, name: "Data science", category: 4 },
        { id: 230, name: "Nanotechnology", category: 11 },
        { id: 231, name: "Stereochemistry", category: 3 },
        { id: 232, name: "Statistical physics", category: 15 },
        { id: 233, name: "Crystallography", category: 3 },
        { id: 234, name: "Criminology", category: 18 },
        { id: 235, name: "Simulation", category: 6 },
        { id: 236, name: "Statistics", category: 12 },
        { id: 237, name: "Thermodynamics", category: 15 },
        { id: 238, name: "Pediatrics", category: 13 },
        { id: 239, name: "Manufacturing engineering", category: 6 },
        { id: 240, name: "Architectural engineering", category: 6 },
        { id: 241, name: "Construction engineering", category: 6 },
        { id: 242, name: "Audiology", category: 13 },
        { id: 243, name: "Chemical engineering", category: 6 },
        { id: 244, name: "Alternative medicine", category: 13 },
        { id: 245, name: "Forensic engineering", category: 6 },
        { id: 246, name: "Medicinal chemistry", category: 3 },
        { id: 247, name: "Pulp and paper industry", category: 6 },
        { id: 248, name: "Water resource management", category: 7 },
        { id: 249, name: "Calculus", category: 12 },
        { id: 250, name: "Management", category: 5 },
        { id: 251, name: "Engineering drawing", category: 6 },
        { id: 252, name: "Mining engineering", category: 9 },
        { id: 253, name: "Nuclear chemistry", category: 3 },
        { id: 254, name: "Radiochemistry", category: 3 },
        { id: 255, name: "Classical economics", category: 5 },
        { id: 256, name: "Process engineering", category: 6 },
        { id: 257, name: "Computational physics", category: 15 },
        { id: 258, name: "Toxicology", category: 1 },
        { id: 259, name: "Acoustics", category: 15 },
        { id: 260, name: "Physical medicine and rehabilitation", category: 13 },
        { id: 261, name: "Astrobiology", category: 15 },
        { id: 262, name: "Automotive engineering", category: 6 },
        { id: 263, name: "Transport engineering", category: 6 },
        { id: 264, name: "Biotechnology", category: 1 },
        { id: 265, name: "Agricultural engineering", category: 6 },
        { id: 266, name: "Petroleum engineering", category: 9 },
        { id: 267, name: "Biochemical engineering", category: 6 },
        { id: 268, name: "Cartography", category: 8 },
        { id: 269, name: "Computational science", category: 12 },
        { id: 270, name: "Dentistry", category: 13 },
        { id: 271, name: "Orthodontics", category: 13 },
        { id: 272, name: "Engineering ethics", category: 6 },
        { id: 273, name: "Chromatography", category: 3 },
        { id: 274, name: "Environmental ethics", category: 14 },
        { id: 275, name: "Geometry", category: 12 },
        { id: 276, name: "Andrology", category: 13 },
        { id: 277, name: "Applied psychology", category: 17 },
        { id: 278, name: "Humanities", category: 14 },
        { id: 279, name: "Biomedical engineering", category: 13 },
        { id: 280, name: "Reliability engineering", category: 6 },
        { id: 281, name: "Marine engineering", category: 6 },
        { id: 282, name: "Combinatorial chemistry", category: 3 },
        { id: 283, name: "Urology", category: 13 },
        { id: 284, name: "Library science", category: 4 },
        { id: 285, name: "Nuclear engineering", category: 6 },
        { id: 286, name: "Genealogy", category: 10 },
        { id: 287, name: "Dermatology", category: 13 },
        { id: 288, name: "Biological system", category: 1 },
        { id: 289, name: "Arithmetic", category: 12 },
        { id: 290, name: "Engineering physics", category: 15 },
        { id: 291, name: "Ceramic materials", category: 11 },
        { id: 292, name: "Computer graphics (images)", category: 4 },
      ],
      links: [
        { source: 0, target: 1 },
        { source: 2, target: 0 },
        { source: 3, target: 4 },
        { source: 3, target: 172 },
        { source: 5, target: 6 },
        { source: 7, target: 8 },
        { source: 8, target: 74 },
        { source: 8, target: 175 },
        { source: 9, target: 10 },
        { source: 9, target: 29 },
        { source: 9, target: 35 },
        { source: 10, target: 182 },
        { source: 11, target: 12 },
        { source: 11, target: 43 },
        { source: 11, target: 218 },
        { source: 12, target: 20 },
        { source: 12, target: 152 },
        { source: 13, target: 14 },
        { source: 13, target: 42 },
        { source: 14, target: 5 },
        { source: 15, target: 5 },
        { source: 16, target: 17 },
        { source: 16, target: 173 },
        { source: 18, target: 19 },
        { source: 18, target: 51 },
        { source: 21, target: 22 },
        { source: 21, target: 116 },
        { source: 21, target: 160 },
        { source: 22, target: 23 },
        { source: 24, target: 6 },
        { source: 25, target: 26 },
        { source: 27, target: 28 },
        { source: 28, target: 191 },
        { source: 29, target: 158 },
        { source: 30, target: 31 },
        { source: 30, target: 47 },
        { source: 32, target: 33 },
        { source: 32, target: 16 },
        { source: 32, target: 249 },
        { source: 33, target: 57 },
        { source: 34, target: 35 },
        { source: 34, target: 11 },
        { source: 34, target: 115 },
        { source: 36, target: 37 },
        { source: 38, target: 24 },
        { source: 38, target: 26 },
        { source: 39, target: 40 },
        { source: 40, target: 191 },
        { source: 41, target: 42 },
        { source: 41, target: 31 },
        { source: 41, target: 133 },
        { source: 42, target: 159 },
        { source: 43, target: 37 },
        { source: 44, target: 6 },
        { source: 45, target: 46 },
        { source: 45, target: 235 },
        { source: 46, target: 169 },
        { source: 47, target: 118 },
        { source: 48, target: 49 },
        { source: 49, target: 105 },
        { source: 50, target: 51 },
        { source: 50, target: 68 },
        { source: 50, target: 270 },
        { source: 52, target: 27 },
        { source: 52, target: 97 },
        { source: 52, target: 98 },
        { source: 52, target: 87 },
        { source: 53, target: 54 },
        { source: 55, target: 56 },
        { source: 55, target: 85 },
        { source: 56, target: 150 },
        { source: 58, target: 26 },
        { source: 58, target: 79 },
        { source: 59, target: 60 },
        { source: 61, target: 62 },
        { source: 61, target: 107 },
        { source: 61, target: 153 },
        { source: 61, target: 156 },
        { source: 63, target: 64 },
        { source: 64, target: 87 },
        { source: 65, target: 66 },
        { source: 67, target: 31 },
        { source: 68, target: 54 },
        { source: 68, target: 171 },
        { source: 69, target: 49 },
        { source: 70, target: 71 },
        { source: 70, target: 174 },
        { source: 70, target: 105 },
        { source: 72, target: 73 },
        { source: 74, target: 75 },
        { source: 76, target: 77 },
        { source: 76, target: 215 },
        { source: 78, target: 54 },
        { source: 78, target: 1 },
        { source: 78, target: 273 },
        { source: 80, target: 81 },
        { source: 81, target: 146 },
        { source: 81, target: 154 },
        { source: 82, target: 83 },
        { source: 82, target: 91 },
        { source: 82, target: 157 },
        { source: 83, target: 106 },
        { source: 83, target: 129 },
        { source: 84, target: 85 },
        { source: 85, target: 199 },
        { source: 86, target: 87 },
        { source: 86, target: 95 },
        { source: 88, target: 6 },
        { source: 89, target: 49 },
        { source: 89, target: 102 },
        { source: 90, target: 91 },
        { source: 91, target: 42 },
        { source: 92, target: 93 },
        { source: 92, target: 105 },
        { source: 92, target: 209 },
        { source: 94, target: 27 },
        { source: 95, target: 96 },
        { source: 97, target: 219 },
        { source: 99, target: 100 },
        { source: 99, target: 187 },
        { source: 99, target: 188 },
        { source: 100, target: 117 },
        { source: 100, target: 134 },
        { source: 100, target: 152 },
        { source: 101, target: 102 },
        { source: 101, target: 257 },
        { source: 103, target: 104 },
        { source: 104, target: 144 },
        { source: 105, target: 232 },
        { source: 106, target: 191 },
        { source: 107, target: 108 },
        { source: 107, target: 103 },
        { source: 109, target: 38 },
        { source: 110, target: 111 },
        { source: 110, target: 60 },
        { source: 111, target: 154 },
        { source: 112, target: 107 },
        { source: 112, target: 227 },
        { source: 113, target: 94 },
        { source: 114, target: 115 },
        { source: 119, target: 120 },
        { source: 121, target: 122 },
        { source: 121, target: 202 },
        { source: 123, target: 54 },
        { source: 123, target: 74 },
        { source: 123, target: 163 },
        { source: 124, target: 120 },
        { source: 124, target: 126 },
        { source: 125, target: 24 },
        { source: 126, target: 23 },
        { source: 127, target: 128 },
        { source: 129, target: 201 },
        { source: 129, target: 150 },
        { source: 130, target: 131 },
        { source: 130, target: 41 },
        { source: 132, target: 110 },
        { source: 135, target: 136 },
        { source: 136, target: 187 },
        { source: 137, target: 138 },
        { source: 139, target: 120 },
        { source: 140, target: 73 },
        { source: 141, target: 20 },
        { source: 142, target: 143 },
        { source: 142, target: 162 },
        { source: 142, target: 183 },
        { source: 143, target: 137 },
        { source: 145, target: 133 },
        { source: 147, target: 129 },
        { source: 148, target: 48 },
        { source: 148, target: 254 },
        { source: 149, target: 121 },
        { source: 149, target: 178 },
        { source: 149, target: 230 },
        { source: 151, target: 58 },
        { source: 152, target: 153 },
        { source: 154, target: 150 },
        { source: 155, target: 156 },
        { source: 155, target: 73 },
        { source: 155, target: 248 },
        { source: 156, target: 274 },
        { source: 157, target: 167 },
        { source: 157, target: 263 },
        { source: 160, target: 166 },
        { source: 161, target: 162 },
        { source: 161, target: 141 },
        { source: 161, target: 216 },
        { source: 162, target: 66 },
        { source: 163, target: 164 },
        { source: 165, target: 93 },
        { source: 165, target: 127 },
        { source: 168, target: 169 },
        { source: 170, target: 68 },
        { source: 171, target: 172 },
        { source: 173, target: 84 },
        { source: 173, target: 22 },
        { source: 173, target: 168 },
        { source: 176, target: 26 },
        { source: 176, target: 177 },
        { source: 179, target: 154 },
        { source: 180, target: 181 },
        { source: 180, target: 31 },
        { source: 184, target: 31 },
        { source: 185, target: 67 },
        { source: 186, target: 83 },
        { source: 188, target: 266 },
        { source: 189, target: 180 },
        { source: 190, target: 156 },
        { source: 192, target: 97 },
        { source: 192, target: 3 },
        { source: 193, target: 98 },
        { source: 194, target: 195 },
        { source: 194, target: 206 },
        { source: 195, target: 204 },
        { source: 195, target: 283 },
        { source: 196, target: 40 },
        { source: 197, target: 198 },
        { source: 198, target: 206 },
        { source: 200, target: 201 },
        { source: 202, target: 210 },
        { source: 202, target: 231 },
        { source: 203, target: 204 },
        { source: 205, target: 96 },
        { source: 205, target: 258 },
        { source: 206, target: 219 },
        { source: 206, target: 238 },
        { source: 207, target: 94 },
        { source: 208, target: 157 },
        { source: 208, target: 239 },
        { source: 209, target: 57 },
        { source: 210, target: 211 },
        { source: 212, target: 213 },
        { source: 212, target: 60 },
        { source: 214, target: 191 },
        { source: 215, target: 23 },
        { source: 216, target: 180 },
        { source: 217, target: 169 },
        { source: 220, target: 221 },
        { source: 220, target: 230 },
        { source: 222, target: 223 },
        { source: 223, target: 264 },
        { source: 224, target: 144 },
        { source: 225, target: 26 },
        { source: 225, target: 236 },
        { source: 226, target: 227 },
        { source: 228, target: 203 },
        { source: 229, target: 154 },
        { source: 233, target: 71 },
        { source: 233, target: 231 },
        { source: 234, target: 180 },
        { source: 237, target: 122 },
        { source: 240, target: 241 },
        { source: 241, target: 263 },
        { source: 242, target: 94 },
        { source: 242, target: 260 },
        { source: 243, target: 230 },
        { source: 244, target: 86 },
        { source: 245, target: 187 },
        { source: 246, target: 231 },
        { source: 247, target: 134 },
        { source: 250, target: 106 },
        { source: 251, target: 239 },
        { source: 252, target: 43 },
        { source: 253, target: 254 },
        { source: 255, target: 88 },
        { source: 256, target: 134 },
        { source: 259, target: 146 },
        { source: 261, target: 101 },
        { source: 262, target: 263 },
        { source: 262, target: 281 },
        { source: 264, target: 163 },
        { source: 265, target: 248 },
        { source: 267, target: 256 },
        { source: 268, target: 158 },
        { source: 269, target: 126 },
        { source: 270, target: 271 },
        { source: 272, target: 129 },
        { source: 275, target: 93 },
        { source: 276, target: 19 },
        { source: 277, target: 28 },
        { source: 278, target: 216 },
        { source: 279, target: 203 },
        { source: 280, target: 199 },
        { source: 282, target: 246 },
        { source: 284, target: 181 },
        { source: 285, target: 254 },
        { source: 286, target: 96 },
        { source: 287, target: 194 },
        { source: 288, target: 267 },
        { source: 289, target: 126 },
        { source: 290, target: 220 },
        { source: 291, target: 252 },
        { source: 292, target: 200 },
      ],
      categories: [
        { name: "Art" },
        { name: "Biology" },
        { name: "Business" },
        { name: "Chemistry" },
        { name: "Computer Science" },
        { name: "Economics" },
        { name: "Engineering" },
        { name: "Environmental science" },
        { name: "Geography" },
        { name: "Geology" },
        { name: "History" },
        { name: "Materials Science" },
        { name: "Mathematics" },
        { name: "Medicine" },
        { name: "Philosophy" },
        { name: "Physics" },
        { name: "Political Science" },
        { name: "Psychology" },
        { name: "Sociology" },
      ],
    };
    graphTitle = "二级学科的最小生成树";
  }
  // else if (appStore.states.graphModeSelect === 3) {
  //   graphTitle = "二级学科的最小生成树";
  // }

  let option = {
    title: {
      left: "center",
      show: false,
      top: "1%",
      textAlign: "center",
      textStyle: {
        fontSize: 20,
      },
      text: graphTitle,
    },
    legend: {
      show: true,
      left: "auto",
      orient: "vertical",
    },
    color: colormap({
      colormap: "hsv",
      // colormap: "rainbow-soft",
      nshades: 19,
      format: "rgbaString",
      alpha: 0.99,
    }).reverse(),
    series: [
      {
        name: "subject",
        type: "graph",
        layout: "force",
        draggable: "true",
        data: graph.nodes,
        links: graph.links,
        categories: graph.categories,
        roam: true,
        zoom: 1.2,
        label: {
          show: labelShow.value,
          position: "top",
        },
        force: {
          repulsion: 100,
          layoutAnimation: true,
        },
      },
    ],
  };
  console.log("set opion:", option);
  myChartObjs[0].setOption(option, true);
}, 1000);

onMounted(() => {
  let elem = document.getElementById("echart1");
  if (elem) {
    myChartObjs.push(echarts.init(elem));
  }

  updateChart();

  window.onresize = _.debounce(() => {
    myChartObjs.forEach((element) => {
      element.resize();
    });
  }, 500);
});
</script>

<style lang="less" scoped>
.echartForce {
  height: 100vh;
}
.card-header {
  .el-row {
    margin: 0;
    .el-col {
      margin: 0;
      .el-tag {
        margin: 0;
      }
    }
  }
}
.el-select {
  width: 95%;
}
.el-card {
  width: 10rem;
  text-align: end;
  .el-row {
    margin: 0;
    .author {
      margin-right: 10px;
      .name {
        white-space: nowrap;
        font-style: normal;
      }
      .org {
        white-space: nowrap;
        font-style: italic;
      }
    }
  }
  .card-header {
    text-align: end;
    .zh {
      font-style: italic;
    }
  }
  .tag {
    .el-tag {
      margin-left: 5px;
    }
  }
}
.el-popper.is-customized {
  /* Set padding to ensure the height is 32px */
  padding: 6px 12px;
  background: linear-gradient(90deg, rgb(159, 229, 151), rgb(204, 229, 129));
}

.el-popper.is-customized .el-popper__arrow::before {
  background: linear-gradient(45deg, #b2e68d, #bce689);
  right: 0;
}
</style>
